#!/usr/bin/env node
/**
 * Generate the Claude Code control plane from the Copilot one.
 *
 * `.github/` is the single source of truth. Claude Code reads a different set
 * of paths and a different frontmatter dialect, so this script translates
 * rather than duplicates:
 *
 *   .github/agents/<x>.agent.md  ->  .claude/agents/<x>.md
 *   .github/skills/<x>/          ->  .claude/skills/<x>/
 *   .github/hooks/agentic-guard.json -> .claude/settings.json
 *   .vscode/mcp.json             ->  .mcp.json
 *
 * The hook SCRIPTS themselves need no translation — they already speak the
 * `hookSpecificOutput` protocol and read `tool_input`. Only the registration
 * wrapper differs: Copilot nests { type, command } directly under the event,
 * Claude nests { matcher, hooks: [...] }.
 *
 * Everything written here is generated. Edit `.github/`, then re-run.
 *
 * Usage: pnpm agents:sync [--check]
 *   --check  exit 1 if the output is stale, without writing (for CI/hooks)
 */

import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  readdirSync,
  statSync,
  existsSync,
} from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const CHECK = process.argv.includes('--check');

const BANNER =
  'GENERATED by .github/hooks/scripts/sync-claude.mjs — edit the .github/ source, then run `pnpm agents:sync`.';

// Every silent drop this script could make, collected for one loud report at the
// end. Fails `agents:sync:check`; see the PROMISES comment for why it is not a
// `stale`-style warning.
const dropWarnings = [];

// ---------------------------------------------------------------------------
// Minimal frontmatter reader.
//
// Deliberately not a full YAML parser. It handles exactly the five shapes that
// can appear in this repo's agent and skill files: scalars, flow sequences
// (`[a, b]`), block sequences (`- a` lines), folded blocks (`>-`), and one level
// of nested map (`metadata:`). Anything else is preserved verbatim rather than
// silently mangled.
// ---------------------------------------------------------------------------

function splitFrontmatter(raw) {
  // Normalise to LF before doing anything else. These files are CRLF on a
  // Windows checkout, and in JS `\r` is a line terminator that `.` will not
  // match — so `/^(key):\s*(.*)$/` silently fails on EVERY line and the parse
  // returns an empty object instead of erroring. Generated output is LF-only;
  // .gitattributes handles the rest.
  const text = raw.replace(/^﻿/, '').replace(/\r\n?/g, '\n');
  if (!text.startsWith('---')) return { fm: null, body: text };
  const end = text.indexOf('\n---', 3);
  if (end === -1) return { fm: null, body: text };
  const block = text.slice(text.indexOf('\n') + 1, end);
  const body = text.slice(text.indexOf('\n', end + 1) + 1);
  return { fm: parseFrontmatter(block), body };
}

function parseFrontmatter(block) {
  const out = {};
  const lines = block.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim() || /^\s*#/.test(line) || /^\s/.test(line)) continue;

    const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const [, key, rest] = m;

    // Folded or literal block scalar: consume the indented continuation.
    if (/^[>|][-+]?$/.test(rest.trim())) {
      const buf = [];
      while (i + 1 < lines.length && (/^\s+\S/.test(lines[i + 1]) || !lines[i + 1].trim())) {
        buf.push(lines[++i].trim());
      }
      out[key] = buf.join(' ').trim();
      continue;
    }

    // Nested map (e.g. `metadata:` with indented children), or a block sequence.
    if (rest.trim() === '') {
      // Block sequences are not hypothetical. `model:` and `tools:` are authored
      // as FLOW sequences today, and the identical list written in block form
      // fell through to the map branch below — whose child regex cannot match a
      // `- item` line — yielding `{}`. `mapModel({})` then returned `inherit`.
      // Two legal spellings of one YAML list produced two different models, with
      // nothing printed. Same silent-drop class as the rest of this file.
      if (/^\s+-\s/.test(lines[i + 1] ?? '')) {
        const seq = [];
        while (i + 1 < lines.length && /^\s+-\s/.test(lines[i + 1])) {
          seq.push(unquote(lines[++i].replace(/^\s*-\s*/, '')));
        }
        out[key] = seq.filter(Boolean);
        continue;
      }

      // ...and the THIRD spelling: a flow sequence WRAPPED onto the following
      // lines. Not exotic — it is the one `prettier` emits. Any `tools: [...]`
      // longer than the print width gets reflowed into a bare `tools:` plus an
      // indented `[ ... ]`, so the repo's own format gate manufactures the form
      // the parser could not read.
      //
      // The failure was total and silent. `[` and `read,` are not `key: value`,
      // so the map branch below matched nothing, `tools` came back `{}`,
      // `mapTools` saw a non-Array and returned null, and the emitter's
      // `if (tools?.length)` dropped the `tools:` line — which in Claude Code
      // does not mean "no tools", it means INHERIT EVERY TOOL.
      //
      // Five of seven agents were unrestricted this way, and the tell is that
      // the only two that survived (`researcher`, `scribe`) are the only two
      // whose lists fit on one line. `reviewer` ("DO NOT edit any file. You have
      // no edit tool"), `memory-updater` ("NEVER call read_graph ... You do not
      // have the tool") and `implementer` ("you have no delegation tool") each
      // held the exact tool its own prompt told it it lacked. Worse, the
      // capability-promise lint below opens with `if (!tools?.length) return`,
      // so those five were exempt from the one check that would have noticed.
      if ((lines[i + 1] ?? '').trim().startsWith('[')) {
        const buf = [];
        while (i + 1 < lines.length) {
          buf.push(lines[++i].trim());
          if (buf[buf.length - 1].endsWith(']')) break;
        }
        out[key] = buf
          .join(' ')
          .replace(/^\[|\]$/g, '')
          .split(',')
          .map((s) => unquote(s.trim()))
          .filter(Boolean);
        continue;
      }

      const child = {};
      while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) {
        const cm = /^\s+([A-Za-z0-9_-]+):\s*(.*)$/.exec(lines[++i]);
        if (cm) child[cm[1]] = unquote(cm[2]);
      }
      out[key] = child;
      continue;
    }

    // Flow sequence.
    if (rest.trim().startsWith('[')) {
      out[key] = rest
        .trim()
        .replace(/^\[|\]$/g, '')
        .split(',')
        .map((s) => unquote(s.trim()))
        .filter(Boolean);
      continue;
    }

    out[key] = unquote(rest.trim());
  }
  return out;
}

// Strip YAML quoting AND resolve escapes. The second half is not decoration: for a
// long time this only stripped the outer quotes, so a double-quoted scalar written
// with \" kept its backslashes, and `yamlString` (JSON.stringify) then escaped those
// backslashes again. A skill description authored as "...asks to \"audit\"..." shipped
// to Claude as literal ...asks to \\"audit\\"..., putting backslashes into the exact
// trigger phrases the description exists to match on. It was invisible in the source
// file and only showed up in the generated one.
const unquote = (s) => {
  const t = String(s).trim();
  if (t.length >= 2 && t.startsWith('"') && t.endsWith('"')) {
    // YAML's double-quoted escapes are a superset-compatible subset of JSON's for
    // everything used here (\" \\ \n \t \uXXXX), so JSON.parse resolves them. Fall
    // back to a bare strip if the scalar is not valid JSON.
    try {
      return JSON.parse(t);
    } catch {
      return t.slice(1, -1).trim();
    }
  }
  // Single-quoted YAML has no backslash escapes at all; '' is the only escape.
  if (t.length >= 2 && t.startsWith("'") && t.endsWith("'")) {
    return t.slice(1, -1).replace(/''/g, "'").trim();
  }
  return t;
};

// ---------------------------------------------------------------------------
// Translation tables
// ---------------------------------------------------------------------------

// Copilot uses abstract capability names; Claude uses concrete tool names.
// Where a tool's name differs between Claude Code CLI and the VS Code agent
// host (Bash/PowerShell, Task/Agent), both are emitted — the field is an
// allowlist filter, so a name that does not exist in a given host is inert.
const TOOLS = {
  read: ['Read'],
  search: ['Grep', 'Glob'],
  edit: ['Edit', 'Write', 'NotebookEdit'],
  execute: ['Bash', 'PowerShell'],
  web: ['WebFetch', 'WebSearch'],
  todo: ['TodoWrite'],
  agent: ['Task', 'Agent'],
  // `skill` grants the Skill tool, which is what lets a subagent load this repo's
  // own skills AND Claude Code's 14 built-ins (`security-review`, `code-review`,
  // `verify`, ...). Without it an agent cannot reach any of them: `tools:` is an
  // allowlist, and a name absent from it is simply not offered.
  //
  // This was a real hole, not a theoretical one. `gsap-framer-scroll-animation`
  // exists to guide exactly the code the implementer writes, and for as long as no
  // agent carried this capability the two could never meet — the skill was reachable
  // only from the main thread, which is not where the code gets written.
  //
  // Grant it to `implementer`, `reviewer` and `debugger` ONLY, and never to
  // `planner`. The reason is recursion, and it turns on the `agent` tool rather than
  // on the skill: `ship-feature`, `review-loop` and `parallel-research` all delegate
  // to named agents, so a holder of BOTH `skill` and `agent` can invoke a skill that
  // re-invokes it. The three agents above have no `agent` tool, so the worst case is
  // a wasted context window, not a loop. The planner has one, so for the planner the
  // worst case is the loop.
  skill: ['Skill'],
};

// Ordered: the FIRST pattern that matches wins, so a mixed preference string
// resolves to the highest tier named in it rather than to the author's order.
// That only matters if `fm.model` ever arrives as one string instead of a list;
// keep the strongest model first so the degenerate case fails upward.
//
// `fable` is a real alias on the installed 2.1.211 — the binary's own help text
// reads "Model override (`haiku`, `sonnet`, `opus`, `fable`, or a full ID)".
// It resolves to Fable 5 there; Fable 5.1 (`claude-fable-5-1`) arrived at
// CHANGELOG 2.1.257, above this binary. It was missing from this table, so a
// source agent preferring it mapped to `inherit` without a word.
const MODELS = [
  [/opus/i, 'opus'],
  [/sonnet/i, 'sonnet'],
  [/fable/i, 'fable'],
  [/haiku/i, 'haiku'],
];

function mapTools(list) {
  if (!Array.isArray(list)) return null;
  const out = [];
  for (const entry of list) {
    if (TOOLS[entry]) {
      out.push(...TOOLS[entry]);
    } else if (entry.startsWith('memory/')) {
      // `memory/*` would be a wildcard; Claude wants the server prefix only.
      const fn = entry.slice('memory/'.length);
      out.push(fn === '*' ? 'mcp__memory' : `mcp__memory__${fn}`);
    } else if (entry.startsWith('sequential-thinking/')) {
      out.push('mcp__sequential-thinking__sequentialthinking');
    } else if (entry.startsWith('context7/')) {
      // Tool names carry HYPHENS, not underscores, and are verified against the
      // live server (Context7 4.1.1) rather than its README: `resolve-library-id`
      // and `query-docs`. The names `resolve_library_id` / `get_library_docs`
      // that upstream guides use do not exist -- see nextjs.instructions.md.
      // A wrong name here is silently dropped below and grants nothing.
      const fn = entry.slice('context7/'.length);
      out.push(
        ...(fn === '*'
          ? ['mcp__context7__resolve-library-id', 'mcp__context7__query-docs']
          : [`mcp__context7__${fn}`]),
      );
    } else if (entry.startsWith('tavily/')) {
      // The server advertises FIVE tools, but only `tavily_search` and
      // `tavily_extract` work without an API key -- the other three answer with
      // "an API key is required". Verified from the server's own startup line:
      // "no TAVILY_API_KEY set; running in keyless mode. Search and extract are
      // available". So `tavily/*` deliberately expands to the two that function,
      // not to all five. Widen this list at the same time you add a key, not
      // before. Names use UNDERSCORES here (unlike context7's hyphens) and were
      // read from the installed build/index.js, not the README.
      const fn = entry.slice('tavily/'.length);
      out.push(
        ...(fn === '*'
          ? ['mcp__tavily__tavily_search', 'mcp__tavily__tavily_extract']
          : [`mcp__tavily__${fn}`]),
      );
    }
    // Unrecognised capability names are dropped rather than passed through —
    // an unknown string in an allowlist is a silent no-op either way, but
    // dropping keeps the generated file honest about what it grants.
  }
  return [...new Set(out)];
}

// Copilot lists a model preference order. Take the first entry that maps to an
// Anthropic model.
//
// `inherit` is a real Claude value, confirmed against the installed 2.1.211's
// own agent-frontmatter schema ("Model override for this agent. Use `inherit` to
// match the spawning conversation.") — but as a FALLBACK it is a lie. It means
// "this file named models I could not map", and it is indistinguishable in the
// generated output from an agent whose tier was deliberately left open. The
// roster's whole value is differential tiering: `inherit` collapses it, silently
// downgrading planner/reviewer/debugger off Opus on a Sonnet session. So the
// fallback still fires — emitting nothing would be worse — but it says so.
function mapModel(sourceFile, list) {
  const arr = Array.isArray(list) ? list : [list].filter(Boolean);
  for (const entry of arr) {
    for (const [re, name] of MODELS) if (re.test(entry)) return name;
  }
  const where = relative(ROOT, sourceFile).split(sep).join('/');
  dropWarnings.push(
    arr.length === 0
      ? `${where}: no \`model:\` resolved — emitting \`inherit\`, which follows the session model and ` +
          `erases this agent's tier. Name a model, or add it to AGENT_DROP_SILENT if that is intended.`
      : `${where}: \`model: ${JSON.stringify(list)}\` matched no entry in MODELS — emitting \`inherit\`. ` +
          `Add the family to MODELS, or write a model this binary knows (opus/sonnet/fable/haiku).`,
  );
  return 'inherit';
}

const slug = (s) =>
  String(s)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const yamlString = (s) => JSON.stringify(String(s).replace(/\s+/g, ' ').trim());

// ---------------------------------------------------------------------------
// Capability-promise lint
// ---------------------------------------------------------------------------
//
// An agent whose PROSE instructs a capability its `tools:` does not GRANT is an
// agent given an order it cannot obey. Nothing errors when this happens: the
// tool is simply absent from the allowlist, the agent improvises, and the gap is
// invisible in review because both halves read correctly on their own.
//
// This has now happened twice in this repo, which is the bar AGENTS.md sets for
// turning a correction into a rule:
//
//   1. Every agent's prose referenced repo skills; NO agent held `Skill`. The
//      `implementer` could not open the 43 KB GSAP skill written for exactly the
//      code it writes. See CONTROL-PLANE-NOTES.md section 12.
//   2. `debugger.agent.md` ordered a `web` search for Next.js 16 API behaviour --
//      "You only get 3 hypotheses" -- while holding neither WebFetch nor
//      WebSearch, nor memory, nor sequentialthinking. Section 12.6.
//
// Prose in the instruction files did not prevent either one, because nothing
// read that prose at the moment it mattered. This does.
//
// Deliberately conservative: each pattern targets a phrase that only appears
// when the agent is being TOLD to use the capability. A false positive here
// would block `agents:sync:check`, and a check that cries wolf gets deleted --
// which is a worse outcome than the gap it guards. Prefer missing a case to
// inventing one, and when adding a pattern, grep the existing seven bodies
// first to confirm it stays silent on them.
const PROMISES = [
  {
    re: /\bweb\b[^.\n]{0,20}\bsearch\b|\bweb-search\b|\bWebSearch\b/i,
    needs: 'WebSearch',
    cap: 'web',
  },
  {
    re: /\bsearch_nodes\b|\bopen_nodes\b|\bknowledge graph\b/i,
    needs: 'mcp__memory__search_nodes',
    cap: 'memory/search_nodes',
  },
  {
    re: /\bsequentialthinking\b/i,
    needs: 'mcp__sequential-thinking__sequentialthinking',
    cap: 'sequential-thinking/*',
  },
  {
    re: /\bresolve-library-id\b|\bquery-docs\b/i,
    needs: 'mcp__context7__query-docs',
    cap: 'context7/*',
  },
  // These two match the FUNCTION names only, never the bare brand word. That is
  // the difference between "use tavily_search to find X" and "you deliberately
  // do not hold `tavily`" -- a regex on `\btavily\b` fires identically on both,
  // because it reads mention and cannot read polarity.
  //
  // It cost four false positives to learn. Every agent that documents which
  // tools it lacks -- which is most of them now, deliberately, because an agent
  // that knows its own limits routes around them instead of guessing -- tripped
  // a guard whose stated contract (see above) is to fire only on instruction.
  // The fix restores that contract rather than punching per-file `allow` holes,
  // which would have switched the rule OFF for the four files most likely to
  // gain a real promise later.
  //
  // Accepted cost: "use tavily to search the web", written without a function
  // name, is no longer caught. That is the block's own trade -- prefer missing
  // a case to inventing one.
  { re: /\btavily_(search|extract)\b/i, needs: 'mcp__tavily__tavily_search', cap: 'tavily/*' },
  { re: /`Skill` tool|\bload the `[a-z0-9-]+` skill\b/i, needs: 'Skill', cap: 'skill' },
];

const promiseWarnings = [];

function lintCapabilityPromises(sourceFile, name, tools, body) {
  // No `tools:` at all means "inherit everything", which cannot under-grant.
  if (!tools?.length) return;
  const granted = new Set(tools);
  for (const { re, needs, cap } of PROMISES) {
    if (!re.test(body) || granted.has(needs)) continue;
    promiseWarnings.push(
      `${relative(ROOT, sourceFile).split(sep).join('/')}: \`${name}\` is instructed to use ` +
        `${needs} but its \`tools:\` does not grant it — add \`${cap}\`, or drop the instruction.`,
    );
  }
}

// ---------------------------------------------------------------------------
// Stale-claim guard
// ---------------------------------------------------------------------------
// `lintCapabilityPromises` above catches an agent told to use a tool it does not
// hold. This catches the other half of the same disease: a claim that has been
// CORRECTED in one file and left standing in another.
//
// That is not hypothetical. Four corrections landed inside 24 hours and every
// one of them reached exactly one file:
//
//   * "Claude registers no hooks"  -> corrected in CONTROL-PLANE-NOTES section 12,
//     still asserted in AGENTS.md and quality-gates, where it was the premise of
//     an operational conclusion ("nothing stops a turn ending with a gate red").
//   * `resolve_library_id` / `get_library_docs` -> corrected in AGENTS.md while
//     nextjs.instructions.md, which loads on EVERY src task, still denied that a
//     context7 server existed at all.
//   * "85% on files changed by the current task" -> contradicted the 90%
//     project-wide threshold in vitest.config.mts, and loaded precisely when
//     tests were being written.
//   * The rules migration -> AGENTS.md updated, root CLAUDE.md left describing
//     generated per-directory CLAUDE.md files that the sync no longer writes.
//
// Prose cannot fix this, because the file that still carries the stale claim is
// by definition the file nobody reread. A string match can.
//
// `allow` lists the files where the string legitimately appears BECAUSE they are
// the correction -- quoting the old wording in order to refute it. Anywhere else
// is a reintroduction. Adding a sixth correction site is meant to require editing
// this list: that edit is the moment you notice you are writing the same
// correction for the sixth time.
//
// Same conservatism as PROMISES: a check that cries wolf gets deleted, which is
// worse than the gap. Every pattern below is verified to match ONLY its allowed
// files as of 2026-09-18. Vendored `skills/*/references/**` is exempt -- it is
// upstream evidence, not repo instruction, and its `npm install gsap` lines are
// already overridden in the SKILL.md that loads with them.
const CLAIM_SCAN_EXEMPT = /[\\/]skills[\\/][^\\/]+[\\/]references[\\/]/;

const STALE_CLAIMS = [
  {
    re: /Claude registers no hooks\b/,
    what: 'says Claude registers no hooks',
    fix: 'Two prompt hooks (Stop, SubagentStop) ARE live. Only *command* hooks are absent — say "no command hooks".',
    allow: ['.github/instructions/quality-gates.instructions.md', '.github/CONTROL-PLANE-NOTES.md'],
  },
  {
    re: /resolve_library_id|get_library_docs/,
    what: 'uses the underscore context7 tool names',
    fix: 'The real tools are `resolve-library-id` and `query-docs` — hyphens. The underscore names do not exist.',
    allow: [
      '.github/CONTROL-PLANE-NOTES.md',
      '.github/instructions/agentic-workflow.instructions.md',
      '.github/instructions/nextjs.instructions.md',
      'AGENTS.md',
    ],
  },
  {
    re: /First Load JS/,
    what: 'asks for a First Load JS figure',
    fix: 'Turbopack emits no size column and no route table. Gate 9 measures total gzipped `.next/static` bytes instead.',
    allow: ['.github/agents/reviewer.agent.md', '.github/CONTROL-PLANE-NOTES.md'],
  },
  {
    re: /\bppnpm\b/,
    what: 'contains the `ppnpm` typo',
    fix: 'Gate 8 silently never ran for its entire existence because of this. The command is `pnpm audit --prod --audit-level=high`.',
    allow: [
      '.github/CONTROL-PLANE-NOTES.md',
      '.github/instructions/quality-gates.instructions.md',
      '.github/skills/dependency-audit/SKILL.md',
    ],
  },
  {
    re: /on files changed by the current task|\b85\s?%[^.\n]{0,40}(?:coverage|statements|changed)/i,
    what: 'states a changed-files coverage bar',
    fix: 'Coverage is 90% PROJECT-WIDE in vitest.config.mts and .husky/pre-commit. A changed-files bar has never existed here.',
    allow: ['.github/instructions/testing.instructions.md', '.github/CONTROL-PLANE-NOTES.md'],
  },
  {
    re: /^[ \t]*(?:\$[ \t]*)?(?:npm|npx)[ \t]+(?:install|i|ci|exec|run)\b/m,
    what: 'has a runnable `npm`/`npx` command line',
    fix: 'This repo is pnpm-only and both binaries are denied in permissions.json. Use `pnpm add` / `pnpm exec`.',
    allow: [],
  },
];

const claimWarnings = [];

function lintStaleClaims() {
  const roots = [join(ROOT, '.github')];
  const files = [];
  const collect = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) collect(abs);
      else if (entry.name.endsWith('.md') && !CLAIM_SCAN_EXEMPT.test(abs)) files.push(abs);
    }
  };
  for (const r of roots) if (existsSync(r)) collect(r);
  for (const name of ['AGENTS.md', 'CLAUDE.md']) {
    const abs = join(ROOT, name);
    if (existsSync(abs)) files.push(abs);
  }

  for (const abs of files) {
    const rel = relative(ROOT, abs).split(sep).join('/');
    const text = readFileSync(abs, 'utf8');
    for (const { re, what, fix, allow } of STALE_CLAIMS) {
      if (allow.includes(rel) || !re.test(text)) continue;
      const line = text.split(/\r?\n/).findIndex((l) => re.test(l)) + 1;
      claimWarnings.push(`${rel}${line ? `:${line}` : ''}: ${what}. ${fix}`);
    }
  }

  // Structural, not textual, and it encodes a standing instruction from the repo
  // owner rather than a fact about the tooling: bypass mode is theirs to enable
  // when they need it, and a settings file must never make that decision for
  // them. The forwarder in buildSettings() stays -- this is what keeps the key
  // from arriving at it.
  const permsPath = join(ROOT, '.github', 'hooks', 'permissions.json');
  if (existsSync(permsPath)) {
    const perms = JSON.parse(readFileSync(permsPath, 'utf8'));
    if (perms.disableBypassPermissionsMode !== undefined) {
      claimWarnings.push(
        '.github/hooks/permissions.json: sets `disableBypassPermissionsMode`. ' +
          'The repo owner removed this deliberately and asked that it not be re-added at ANY value — ' +
          "it is their switch to throw, not the settings file's. Delete the key.",
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Emitters

// ---------------------------------------------------------------------------

function buildAgent(file) {
  const { fm, body } = splitFrontmatter(readFileSync(file, 'utf8'));
  if (!fm) throw new Error(`No frontmatter in ${file}`);
  // Fail loudly. Falling back to a filename here is how a parser bug turns
  // into seven agents silently named after their own paths.
  if (!fm.name) throw new Error(`No "name" in frontmatter of ${file}`);
  if (!fm.description) throw new Error(`No "description" in frontmatter of ${file}`);

  const name = slug(fm.name);
  const tools = mapTools(fm.tools);

  lintCapabilityPromises(file, name, tools, body);

  const lines = ['---', `name: ${name}`, `description: ${yamlString(fm.description)}`];
  if (tools?.length) lines.push(`tools: ${tools.join(', ')}`);
  lines.push(
    `model: ${mapModel(file, fm.model)}`,
    '---',
    '',
    `<!-- ${BANNER} -->`,
    '',
    body.trimStart(),
  );

  // `agents:` (which subagents a Copilot agent may spawn) has no Claude
  // equivalent — delegation is granted wholesale by the Task tool. Surface it
  // as prose so the orchestration contract is not silently lost.
  if (Array.isArray(fm.agents) && fm.agents.length) {
    const names = fm.agents.map(slug).join('`, `');
    lines.splice(
      lines.indexOf(`<!-- ${BANNER} -->`) + 1,
      0,
      '',
      `> **Delegation targets:** \`${names}\`. Claude grants delegation wholesale via the Task tool rather than`,
      '> restricting it per-agent, so treat this list as binding: do not spawn subagents outside it.',
    );
  }

  lintAgentFrontmatter(file, fm);

  return { path: join('.claude', 'agents', `${name}.md`), content: lines.join('\n') };
}

// Same guard as the skill emitter below, for the same reason. Everything this
// function does NOT name is dropped on the floor, so the only safe design is to
// enumerate both outcomes and warn on the remainder.
//
// `argument-hint` and `user-invocable` are Copilot-isms here, NOT Claude agent
// fields -- `user-invocable` is a SKILL field (CHANGELOG 2.1.0: "opt-out with
// `user-invocable: false` in frontmatter", about skills in `/skills/`), and
// `argument-hint` has changelog support for commands and skills but never for
// agents. Dropping both is correct; dropping them silently was not.
//
// The warn path matters most in the OTHER direction. Claude does support real
// agent frontmatter this repo deliberately declines -- `memory:` (2.1.33),
// `isolation: worktree` (2.1.50), `background: true` (2.1.49), `hooks:` (2.1.0),
// `disallowedTools` (2.0.30), `mcpServers` (2.1.117). Each is redundant against
// an allowlist, or reintroduces the console-flash hooks banned in section 1.
// Writing one into a source agent and having it vanish is exactly the failure
// this repo has now paid for four times.
const AGENT_EMITTED = ['name', 'description', 'tools', 'model'];
const AGENT_DROP_SILENT = ['agents', 'argument-hint', 'user-invocable'];

function lintAgentFrontmatter(sourceFile, fm) {
  const where = relative(ROOT, sourceFile).split(sep).join('/');
  for (const key of Object.keys(fm)) {
    if (AGENT_EMITTED.includes(key) || AGENT_DROP_SILENT.includes(key)) continue;
    dropWarnings.push(
      `${where}: \`${key}\` is not emitted to .claude/agents/ — add it to AGENT_EMITTED if Claude ` +
        `parses it on agents, or to AGENT_DROP_SILENT if it is Copilot-only.`,
    );
  }
}

// Claude Code SKILL.md frontmatter -- the fourth instance of the silent-drop
// class documented in the PROMISES comment above.
//
// This emitter used to write `name` + `description` and nothing else, under a
// comment asserting that is all Claude skills take. It is not. `argument-hint`
// is a genuine SKILL.md field: CHANGELOG 2.1.47 fixes a React crash parsing
// `argument-hint` IN SKILL.md frontmatter, and 2.1.149 fixes it not appearing
// after Tab-completing a skill. You cannot crash on a field you do not parse.
// FIVE of this repo's six skills author one, and all five were discarded -- so
// every slash command in AGENTS.md shipped without the hint its author wrote.
//
// The lesson is the same one section 11.4 got wrong: absence from upstream's
// EXAMPLES is evidence about convention, not about the parser. Only the
// changelog and the binary speak to what is parsed.
const SKILL_PASSTHROUGH = [
  'argument-hint', // 2.0.0; SKILL.md-specific fixes at 2.1.47 and 2.1.149
  'disallowed-tools', // 2.1.152 "Skills and slash commands can now set..."
  'effort', // 2.1.80 -- but see 2.1.267: ignored on effort-pinned models
];

// No Claude equivalent. Dropping these is correct, so it stays silent.
const SKILL_DROP_SILENT = ['name', 'description', 'metadata'];

function skillFrontmatter(sourceFile, fm) {
  const lines = [];
  for (const key of SKILL_PASSTHROUGH) {
    if (fm[key] !== undefined) lines.push(`${key}: ${yamlString(String(fm[key]))}`);
  }

  const where = relative(ROOT, sourceFile).split(sep).join('/');
  for (const key of Object.keys(fm)) {
    if (SKILL_PASSTHROUGH.includes(key) || SKILL_DROP_SILENT.includes(key)) continue;
    // `allowed-tools` is real on skills (2.0.74, YAML lists 2.1.0) but it
    // AUTO-APPROVES what it names -- 2.1.69 had to fix interactive tools being
    // "silently auto-allowed when listed in a skill's allowed-tools, bypassing
    // the permission prompt". This repo keeps its permission surface in one
    // reviewable place, `.github/hooks/permissions.json`, so a skill file does
    // not get to widen it. Refused loudly rather than dropped quietly.
    dropWarnings.push(
      key === 'allowed-tools'
        ? `${where}: \`allowed-tools\` auto-approves the tools it names — this repo keeps permissions in ` +
            `.github/hooks/permissions.json. Use \`disallowed-tools\` to narrow, or add the rule there.`
        : `${where}: \`${key}\` is not emitted — add it to SKILL_PASSTHROUGH if Claude parses it, ` +
            `or to SKILL_DROP_SILENT if it is Copilot-only.`,
    );
  }
  return lines;
}

function buildSkill(dir, name) {
  const out = [];
  const src = join(ROOT, '.github', 'skills', name);

  for (const rel of walk(src)) {
    const abs = join(src, rel);
    if (rel === 'SKILL.md') {
      const { fm, body } = splitFrontmatter(readFileSync(abs, 'utf8'));
      if (!fm) throw new Error(`No frontmatter in ${abs}`);
      if (!fm.description) throw new Error(`No "description" in frontmatter of ${abs}`);
      const content = [
        '---',
        `name: ${slug(fm.name || name)}`,
        `description: ${yamlString(fm.description)}`,
        ...skillFrontmatter(abs, fm),
        '---',
        '',
        `<!-- ${BANNER} -->`,
        '',
        body.trimStart(),
      ].join('\n');
      out.push({ path: join('.claude', 'skills', name, 'SKILL.md'), content });
    } else {
      // references/*.md and any other asset copy through untouched (modulo
      // line-ending normalisation, so --check does not thrash on CRLF).
      out.push({
        path: join('.claude', 'skills', name, rel),
        content: readFileSync(abs, 'utf8').replace(/\r\n?/g, '\n'),
      });
    }
  }
  return out;
}

function walk(dir, base = '') {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    const rel = base ? join(base, entry) : entry;
    if (statSync(abs).isDirectory()) out.push(...walk(abs, rel));
    else out.push(rel);
  }
  return out;
}

// Hooks that Copilot runs but Claude does NOT, with the reason each is dropped.
//
// A hook is not free. The host runs `type: "command"` hooks through `cmd /c`,
// which on Windows allocates a console -- a window that flashes on screen for
// every matching tool call -- and blocks that call for ~70ms while node starts.
// Paying that on Read and Edit, the two highest-frequency tools in any session,
// buys nothing that Claude cannot do better in-process.
//
// Copilot keeps all of these: it has no native permission system and no
// always-loaded instruction equivalent, so for Copilot the hook IS the mechanism.
const CLAUDE_SKIP = {
  'guard-writes':
    'every rule in it is path-based, and path rules belong in `permissions` where Claude ' +
    'enforces them in-process -- no spawn, no window, no latency, and they still hold when ' +
    'node cannot be found. See permissions.json.',
  'gate-reminder':
    'its message duplicates quality-gates.instructions.md, which has no `applyTo` and is ' +
    'therefore imported by the root CLAUDE.md on every single turn. A console window per ' +
    'edit to repeat text already in context is a bad trade.',
  'date-context':
    'the harness injects the current date natively -- it was present in context during a ' +
    'session in which these hooks provably never executed, which is the proof.',
  'guard-shell':
    'it hung. Under `cmd /c` the child node process never saw stdin close, so it blocked ' +
    'forever on the `end` event, `cmd.exe` stayed alive waiting for it, and its console ' +
    'window stayed on screen -- observed 2026-09-17 as ~11 live cmd/conhost/node trios up ' +
    'to 4.6 minutes old. The registered `timeout` did not reap them. A guard that leaves ' +
    'windows littered across the desktop gets the whole system switched off, which protects ' +
    'nothing. Its prefix-expressible rules moved to permissions.json; see the note there for ' +
    'exactly what is no longer covered.',
};

// The console window cannot be suppressed from inside this repo -- the host owns
// the spawn and does not pass windowsHide -- and a hook that hangs leaves that
// window on screen indefinitely. Claude therefore registers NO hooks at all: every
// rule it enforces is native, in-process, and cannot leak a process. Copilot still
// registers all four, because it has no permission system and the hook IS its only
// mechanism -- but see the stdin watchdog in the scripts, added so a hang there
// cannot litter windows either.

// Which tools each hook actually cares about. Copilot's format has no matcher
// field, so this mapping is inherently Claude-specific and lives here.
const MATCHERS = {
  // Shell commands only; the script exits immediately on anything else. This is
  // the one guard Claude still runs, because it matches command CONTENT --
  // `--no-verify` anywhere in a chain, `rm -rf` after a `&&` -- which the
  // prefix-based native rules cannot express.
  'guard-shell': 'Bash|PowerShell',
  'guard-writes': 'Edit|Write|NotebookEdit|Read|NotebookRead',
  'gate-reminder': 'Edit|Write|NotebookEdit',
  // Every tool that can name a path or carry a payload. Bash/PowerShell are in
  // scope because a secret can be read through a shell command, which is the
  // one thing native Read(...) deny rules cannot see inside.
  guardrail: 'Bash|PowerShell|Read|Edit|Write|NotebookEdit|NotebookRead',
};

// Hooks are launched through a wrapper rather than bare `node` so that a
// missing or broken interpreter reports itself instead of silently disarming
// every guard. See run-hook.cmd for the full reasoning.
const LAUNCHER = '.github\\hooks\\scripts\\run-hook.cmd';

// The Python twin. `guardrail.py` is the one PreToolUse COMMAND hook Claude
// registers, and it is spawned through its own launcher for the same
// silent-failure reason -- see run-pyhook.cmd.
//
// Why this one is registered when all four .mjs hooks are in CLAUDE_SKIP: the
// blanket ban existed because command hooks HUNG on Windows, leaving console
// windows open indefinitely (CLAUDE_SKIP['guard-shell'] records the 2026-09-17
// forensics). That specific failure was re-measured on 2026-09-22 with an
// instrumented probe of the identical shape and is GONE -- stdin now closes in
// ~5ms, every process is reaped, and counts return to baseline. What remains is
// a per-invocation cmd/conhost/node trio lasting milliseconds, which is a cost
// rather than a breakage. guardrail.py is worth that cost where the .mjs hooks
// were not, because it inspects tool-input CONTENT for secret material, which
// prefix-based native rules structurally cannot do.
// Note the path: this points at the GENERATED copy under `.claude/hooks/`, not
// at the `.github/` source. The launcher resolves its script via `%~dp0`, so the
// two files travel together, and it keeps the registered command inside the tree
// Claude Code owns. Both copies are emitted and stale-checked by this script, so
// they cannot drift apart silently.
const PY_LAUNCHER = '.claude\\hooks\\run-pyhook.cmd';

// Interpreter-agnostic hook sources, copied verbatim into `.claude/hooks/` so
// the generated tree is self-describing. Emitted as ordinary artifacts, which
// means stale-detection, `--check` and orphan sweeping all cover them for free.
const HOOK_ASSETS = ['guardrail.py', 'run-pyhook.cmd'];

function buildHookAssets() {
  return HOOK_ASSETS.map((name) => ({
    path: join('.claude', 'hooks', name),
    content: readFileSync(join(ROOT, '.github', 'hooks', 'scripts', name), 'utf8'),
  }));
}

function buildSettings() {
  const src = JSON.parse(
    readFileSync(join(ROOT, '.github', 'hooks', 'agentic-guard.json'), 'utf8'),
  );
  const hooks = {};
  const skipped = [];

  // Copilot:  event -> [ { type, command } ]
  // Claude:   event -> [ { matcher, hooks: [ { type, command } ] } ]
  //
  // Claude also groups by matcher, so each script becomes its own entry rather
  // than sharing one wildcard bucket.
  for (const [event, entries] of Object.entries(src.hooks ?? {})) {
    for (const entry of entries) {
      // Accept both spellings of the source command: the launcher form
      // (`run-hook.cmd guard-shell`) and the older bare-node form
      // (`node ./.github/hooks/scripts/guard-shell.mjs`). Either way what we
      // need is the script basename, which selects the matcher below.
      const script =
        /([\w-]+)\.(?:mjs|py)/.exec(entry.command)?.[1] ?? entry.command.trim().split(/\s+/).pop();
      // Resolve which interpreter owns it by finding the source file. A hook
      // named in agentic-guard.json with no script on disk is a hard error, not
      // a warning -- it would register, fail to start, and be read as "approve".
      const ext = ['mjs', 'py'].find((e) =>
        existsSync(join(ROOT, '.github', 'hooks', 'scripts', `${script}.${e}`)),
      );
      if (!script || !ext) {
        throw new Error(`Cannot identify hook script in: ${entry.command}`);
      }
      if (CLAUDE_SKIP[script]) {
        skipped.push(script);
        continue;
      }
      const inner = {
        type: 'command',
        command: `${ext === 'py' ? PY_LAUNCHER : LAUNCHER} ${script}`,
        timeout: entry.timeout,
      };
      // UserPromptSubmit is not a tool event and takes no matcher.
      // Only create the event key once a hook actually lands in it, so a fully
      // skipped event does not emit an empty array.
      hooks[event] ??= [];
      hooks[event].push(
        event === 'UserPromptSubmit'
          ? { hooks: [inner] }
          : { matcher: MATCHERS[script] ?? '*', hooks: [inner] },
      );
    }
  }

  if (skipped.length) {
    console.log(
      `[sync-claude] Copilot-only hooks (Claude covers these natively): ${[...new Set(skipped)].join(', ')}`,
    );
  }

  // Prompt-type hooks. Claude-only, and a genuinely different mechanism from the
  // command hooks above: the host spawns NOTHING. So neither reason the command
  // hooks are dropped applies here -- there is no `cmd /c`, therefore no console
  // window to flash and nothing that can hang holding one open. They were also
  // measured on 2026-09-18 to fire on an UNTRUSTED workspace, which
  // `permissions.allow` famously does not.
  //
  // What a prompt hook actually IS matters more than any of that, because getting
  // it wrong is silent and total. It is a CONDITION EVALUATOR -- the same machinery
  // as `/goal` -- not a judge that returns JSON. The host treats `prompt` as a
  // statement that must be TRUE before the turn may end, and on failure injects
  // `Stop hook feedback:\n[<the prompt verbatim>]: <reasoning>` and continues the
  // turn. A prompt phrased as an instruction ("respond {"ok": true} unless...") is
  // therefore read as a requirement that the ASSISTANT emit that JSON. It never
  // does, the condition is never satisfied, and the hook blocks every turn forever.
  // This repo shipped exactly that for one revision; the check below is what stops
  // it coming back. See CONTROL-PLANE-NOTES.md section 11.
  const JUDGE_PHRASING = /respond\s+(?:with\s+)?\{|"ok"\s*:|\{\s*"decision"/i;

  // Only TWO events accept `type: "prompt"`. Everything else takes a command
  // hook, and configuring a prompt on one is the same silent-decoration failure
  // this file already guards three other ways: it emits cleanly into
  // settings.json, `claude doctor` says nothing, and the condition never runs.
  //
  //   Stop          CHANGELOG.md:6192 -> 2.0.30 (introduced)
  //   SubagentStop  CHANGELOG.md:4215 -> 2.1.98
  //
  // The negative is documented too, which is rarer and worth trusting:
  // CHANGELOG.md:3325 -> 2.1.142 added an error for "configuring a prompt- or
  // agent-type hook for SessionStart/Setup/SubagentStart" telling you to use a
  // command-type hook instead. For PreToolUse, PostToolUse, UserPromptSubmit,
  // Notification, PreCompact and SessionEnd there is NO changelog entry granting
  // prompt support in any of the 275 versions scanned -- only command-type
  // semantics. Note that the bundled `plugin-dev` skill's hook-development
  // references show PreToolUse/UserPromptSubmit prompt examples and call them
  // "best supported"; that corpus is plugin-authoring guidance, is not version
  // pinned, and the changelog does not corroborate it. Believe the changelog.
  //
  // Widen this set only against a changelog line that grants the event prompt
  // support, and cite it here the way the two above are cited.
  const PROMPT_HOOK_EVENTS = new Set(['Stop', 'SubagentStop']);

  const promptHooks = [];
  for (const [event, entries] of Object.entries(src.claudePromptHooks ?? {})) {
    if (!PROMPT_HOOK_EVENTS.has(event)) {
      throw new Error(
        `claudePromptHooks.${event}: only ${[...PROMPT_HOOK_EVENTS].join(' and ')} accept type:"prompt". ` +
          `A prompt hook on "${event}" emits into settings.json, passes \`claude doctor\`, and never fires. ` +
          `Use a command hook in \`hooks\` instead, or cite the changelog line that grants ${event} prompt support.`,
      );
    }
    for (const entry of entries) {
      // A prompt hook that is malformed fails the same silent way a command hook
      // with a bad interpreter does -- it reads as configured and decides nothing.
      // Fail the sync loudly instead.
      if (entry.type !== 'prompt' || typeof entry.prompt !== 'string' || !entry.prompt.trim()) {
        throw new Error(
          `claudePromptHooks.${event}: every entry needs type:"prompt" and a non-empty prompt string`,
        );
      }
      if (JUDGE_PHRASING.test(entry.prompt)) {
        throw new Error(
          `claudePromptHooks.${event}: the prompt is phrased as a judge returning JSON ` +
            `("respond {...}" / "ok": / {"decision"). A prompt hook is a CONDITION evaluator, not a judge. ` +
            `Phrased this way the evaluator waits for the assistant to emit that JSON, never sees it, ` +
            `and blocks every turn forever. Rewrite it as a statement that must be true for the turn to ` +
            `end, and name the turns that satisfy it trivially. See CONTROL-PLANE-NOTES.md section 11.`,
        );
      }
      const inner = { type: 'prompt', prompt: entry.prompt };
      if (entry.timeout !== undefined) inner.timeout = entry.timeout;
      hooks[event] ??= [];
      hooks[event].push(
        entry.matcher ? { matcher: entry.matcher, hooks: [inner] } : { hooks: [inner] },
      );
      promptHooks.push(entry.matcher ? `${event}(${entry.matcher})` : event);
    }
  }
  if (promptHooks.length) {
    console.log(
      `[sync-claude] Claude prompt hooks (conditions; no subprocess, no trust needed): ${promptHooks.join(', ')}`,
    );
  }

  // Native permission rules. Enforced by Claude directly, so unlike the hooks
  // they still apply when the interpreter cannot be found.
  const perms = JSON.parse(
    readFileSync(join(ROOT, '.github', 'hooks', 'permissions.json'), 'utf8'),
  );
  const permissions = {};
  for (const key of ['allow', 'ask', 'deny', 'additionalDirectories']) {
    if (Array.isArray(perms[key]) && perms[key].length) permissions[key] = perms[key];
  }
  // Scalar permission keys. Without this the sync silently DROPPED anything that
  // was not one of the three rule arrays, so a hardening flag added to
  // permissions.json would read as configured and never reach settings.json.
  //
  // `defaultMode`: the 2.1.211 schema enum is six values --  acceptEdits, auto,
  // bypassPermissions, default, dontAsk, plan -- not the four an earlier version
  // of this comment listed. Which of them a PROJECT file may set is a separate
  // question and is not verified here; `permissions.json` sets `default`.
  //
  // `blockReadsOutsideWorkingDirectories` is BLOCKED-ON-UPGRADE, not available:
  // it arrived at CHANGELOG.md:896 / 2.1.257 and the installed binary is 2.1.211,
  // where the string does not appear at all. It is forwarded so that the upgrade
  // is the only thing standing between setting it and it working -- but setting
  // it TODAY produces a key that reads as configured and does nothing, because
  // `permissions` is `.passthrough()` and an unknown settings key warns nowhere.
  // That is the exact failure class this repo keeps re-learning. Do not set it
  // until `claude --version` reports >= 2.1.257.
  for (const key of [
    'defaultMode',
    'disableBypassPermissionsMode',
    'blockReadsOutsideWorkingDirectories',
  ]) {
    if (perms[key] !== undefined) permissions[key] = perms[key];
  }

  // Session environment. The agent host here launches its shells with a mangled
  // PATHEXT (observed as literally `.CPL`), which drops `.EXE` and therefore makes
  // every binary on PATH unresolvable -- `node`, `pnpm` and `git` all report "is
  // not recognized" while sitting on PATH, and PowerShell downgrades `foo.exe` to
  // "a document" it cannot pipe. The machine registry is healthy, so this is not
  // something a PATH repair can fix; it has to be re-set per session.
  const env = perms.env && typeof perms.env === 'object' ? perms.env : undefined;

  // Project-scope MCP approval. A server declared in `.mcp.json` does NOT run
  // until it is approved; until then `claude mcp list` shows it as "⏸ Pending
  // approval" and it silently never starts. The interactive prompt writes that
  // answer into ~/.claude.json, which is per-machine and unreviewable, so the
  // approval is declared in permissions.json instead and generated here.
  //
  // The names are cross-checked against the servers actually declared, because
  // the failure mode of a typo or a rename is exactly the bug this key exists
  // to fix -- a server that looks configured and never launches.
  const enabled = perms.enabledMcpjsonServers;
  if (Array.isArray(enabled) && enabled.length) {
    const declared = new Set(
      Object.keys(
        JSON.parse(readFileSync(join(ROOT, '.vscode', 'mcp.json'), 'utf8')).servers ?? {},
      ),
    );
    const unknown = enabled.filter((n) => !declared.has(n));
    if (unknown.length) {
      throw new Error(
        `permissions.json approves MCP server(s) not declared in .vscode/mcp.json: ${unknown.join(', ')}. ` +
          `Declared: ${[...declared].join(', ') || '(none)'}`,
      );
    }
    const unapproved = [...declared].filter((n) => !enabled.includes(n));
    if (unapproved.length) {
      console.log(
        `[sync-claude] MCP servers declared but NOT approved (they will not start): ${unapproved.join(', ')}`,
      );
    }
  }

  const settings = { permissions, hooks };
  if (env) settings.env = env;
  if (Array.isArray(enabled) && enabled.length) settings.enabledMcpjsonServers = enabled;

  // Top-level (non-`permissions`) settings keys. Same allowlist discipline as the
  // scalar permission keys above: forwarded explicitly, each with the CHANGELOG
  // line that proves it exists at or below the installed 2.1.211. A key added
  // here without that check reads as configured and does nothing, because
  // settings objects are `.passthrough()` and `claude doctor` only type-checks
  // the keys it already recognises.
  //
  //   disableSkillShellExecution  CHANGELOG.md:4342 -> 2.1.91
  //     Disables inline shell execution inside skill / slash-command / plugin
  //     bodies -- a code path that runs OUTSIDE the Bash and PowerShell tools and
  //     is therefore invisible to all 167 deny and 41 ask rules. Verified free
  //     here: no file under .github/ uses the inline-exec syntax, so setting it
  //     costs this repo's own six skills nothing. It is pre-emptive cover for
  //     AGENTS.md's documented plan to `claude plugin install example-skills@...`,
  //     which would bring twelve third-party skill bodies nobody here has read.
  //
  //   fallbackModel               CHANGELOG.md:2809 -> 2.1.166
  //     Up to three models tried in order when the primary is overloaded. MUST be
  //     an ARRAY -- `claude doctor` caught this exact key as string-not-array in
  //     the 2026-09-18 probe (see the note on the return value below), which is
  //     the one shape of settings mistake it does report. Every agent in
  //     .github/agents/ pins a tier, so without this an overloaded primary hard-
  //     fails the planner mid-pipeline. One entry, not three, and deliberately a
  //     weaker model: a degraded reviewer still has to paste verbatim gate output
  //     to satisfy the Stop hook, so the evidence requirement survives a downgrade
  //     that a hard failure would simply end.
  //
  // AUTO MODE IS NOT CONFIGURABLE FROM THIS FILE, and the attempt is guarded
  // below rather than merely discouraged. On 2026-09-19 `defaultMode: "auto"`,
  // `skipAutoPermissionPrompt` and a full `autoMode` rulebook were written into
  // `.github/hooks/permissions.json`, forwarded from here, and validated clean --
  // `agents:sync:check` exit 0, `claude doctor` "No installation issues found."
  // Every one of them was inert. Two source gates, read verbatim out of the
  // binary, throw them away at load time:
  //
  //   settings defaultMode "auto" ignored -- only policy/user/flag settings may
  //   grant auto mode (projectSettings and localSettings are repo-controllable)
  //
  //   settings autoMode in ${source} ignored -- only user/flag/managed settings
  //   may set classifier rules (projectSettings and localSettings are
  //   repo-controllable)
  //
  // The mechanism, for anyone tempted to re-litigate it:
  //
  //   var de = ["policySettings","flagSettings","userSettings"];
  //   function C(e){ return de.filter(Wr).some(n => be(n)?.permissions?.defaultMode === e) }
  //   function ae(e){
  //     let n = hp(e.permissions?.defaultMode);
  //     if (n == null || !A(n)) return;
  //     if (n !== "auto") return n;              // every OTHER mode is honoured here
  //     return C("auto") && sYe(e) ? "auto" : void 0;
  //   }
  //
  // `ae` reads the MERGED settings, so a project-scope "auto" reaches it -- and
  // is then dropped unless a TRUSTED source independently declares "auto" too.
  // The point is that a repo you clone must not be able to grant itself
  // autonomous execution on your machine. Reasonable, and non-negotiable.
  //
  // The config now lives in `~/.claude/settings.json` (user scope), which is the
  // only place it is honoured. See .github/CONTROL-PLANE-NOTES.md 12.17.
  //
  // `defaultMode` is left ABSENT from permissions.json rather than pinned, for a
  // reason the binary states outright in its own settings-audit doc: "only the
  // VALUE `auto` is source-restricted -- a project or local
  // `permissions.defaultMode` set to any OTHER mode (`plan`, `acceptEdits`,
  // `default`, ...) is honored and, in the settings cascade (user < project <
  // local), overrides the user-scope `auto`." So pinning `default` here, or
  // taking the tempting-looking `acceptEdits` upgrade, would silently DOWNGRADE
  // the user-scope auto mode to something weaker. Absent is the only value that
  // lets user scope do its job.
  //
  // Keep this next part regardless of where the config lives -- `aVt` is the
  // resolver every mode flows through and it contains a genuine trap:
  //
  //   function aVt(e,t){
  //     if(e==="auto")              return "classify";
  //     if(e==="bypassPermissions") return "allow";
  //     if(e==="dontAsk")           return "deny";
  //     return "ask";
  //   }
  //
  // `dontAsk` does NOT mean "proceed without asking", it means REFUSE without
  // asking. It is in the `defaultMode` enum, it reads like the autonomy setting,
  // and it is the exact opposite of one. `auto` is the mode that buys autonomy.
  //
  // Why the `ask` rule on `git push` survives auto mode: a rule-derived ask sets
  // an ask floor, and the binary's log line for that path reads "ask rule/safety
  // check requires full permission pipeline (hookAskFloor -- a classifier allow
  // re-surfaces as this ask)". A classifier ALLOW cannot clear it.
  for (const key of ['disableSkillShellExecution', 'fallbackModel']) {
    if (perms[key] !== undefined) settings[key] = perms[key];
  }

  // Structural guard, not a style rule. Each of these is silently discarded when
  // it arrives from projectSettings/localSettings, which is precisely the
  // "declared and unreachable" failure this repo keeps re-committing -- it looks
  // configured, validates clean, and does nothing. Fail the sync instead.
  const USER_SCOPE_ONLY = {
    autoMode: 'classifier rulebook -- only user/flag/managed settings may set it',
    skipAutoPermissionPrompt: 'auto-mode opt-in consent -- meaningless without a honoured `auto`',
    useAutoModeDuringPlan: 'read as `!== false` (already defaults true) AND user-scope-only',
  };
  for (const [key, why] of Object.entries(USER_SCOPE_ONLY)) {
    if (perms[key] !== undefined) {
      throw new Error(
        `[sync-claude] permissions.json declares "${key}", which is user-scope-only: ${why}.\n` +
          `  Project settings cannot grant auto mode; the binary drops it with a warn-level log.\n` +
          `  Configure it in ~/.claude/settings.json instead, and see CONTROL-PLANE-NOTES.md 12.17.`,
      );
    }
  }
  if (perms.defaultMode === 'auto') {
    throw new Error(
      `[sync-claude] permissions.json sets defaultMode "auto", which projectSettings may not grant.\n` +
        `  Verbatim from the binary: 'settings defaultMode "auto" ignored -- only policy/user/flag\n` +
        `  settings may grant auto mode (projectSettings and localSettings are repo-controllable)'.\n` +
        `  It belongs in ~/.claude/settings.json. Leave this key ABSENT here: any other value would\n` +
        `  override the user-scope "auto" (cascade is user < project < local).`,
    );
  }

  return {
    // No generation banner in here, because settings.json has no comment syntax
    // that survives a round-trip and the provenance note lives in .claude/README.md
    // instead.
    //
    // An earlier revision justified this differently: "settings.json is
    // schema-validated and an unknown top-level key produces a warning on every
    // launch." That is FALSE, and worth knowing for a much more important reason
    // than the banner. Measured 2026-09-18 against 2.1.211: a settings file
    // containing a deliberate junk key ran a clean session and `claude doctor`
    // reported no finding for it. `doctor` type-checks the keys it RECOGNISES --
    // it caught `fallbackModel` as string-not-array and `sandbox` as
    // boolean-not-object in the same probe -- and silently passes everything it
    // does not. So a MISSPELLED settings key is invisible: no warning, no error,
    // no effect. Same silent-decoration failure class as the `ppnpm audit` typo
    // and the Bash(...)-only shell rules. When adding a key here, confirm the
    // spelling against the docs; nothing downstream will tell you it was wrong.
    path: join('.claude', 'settings.json'),
    content: JSON.stringify(settings, null, 2) + '\n',
  };
}

function buildMcp() {
  const src = JSON.parse(readFileSync(join(ROOT, '.vscode', 'mcp.json'), 'utf8'));
  const mcpServers = {};

  for (const [name, cfg] of Object.entries(src.servers ?? {})) {
    const next = { ...cfg };

    // Claude's only substitutions are `${VAR}` and `${VAR:-default}`; there is
    // no `${workspaceFolder}`. The documented equivalent is CLAUDE_PROJECT_DIR,
    // which Claude sets in the SERVER's environment -- not its own -- so an
    // expansion of it from .mcp.json falls through to the default almost every
    // time. That default therefore has to be a real absolute path, not `.`.
    //
    // This is not pedantry. @modelcontextprotocol/server-memory resolves a
    // relative MEMORY_FILE_PATH against its OWN dist directory, not the CWD:
    //
    //   path.isAbsolute(p) ? p : path.join(path.dirname(import.meta.url), p)
    //
    // so a relative value here would have parked the knowledge graph inside
    // node_modules, silently, while every health check still reported green.
    const reWorkspace = /\$\{workspaceFolder\}/g;
    const CLAUDE_DIR = `\${CLAUDE_PROJECT_DIR:-${ROOT.replace(/\\/g, '/')}}`;

    if (next.env) {
      next.env = Object.fromEntries(
        Object.entries(next.env).map(([k, v]) => [k, String(v).replace(reWorkspace, CLAUDE_DIR)]),
      );
    }
    if (Array.isArray(next.args)) {
      next.args = next.args.map((a) => String(a).replace(reWorkspace, CLAUDE_DIR));
    }
    if (typeof next.command === 'string')
      next.command = next.command.replace(reWorkspace, CLAUDE_DIR);

    // VS Code-only fields. Claude's schema does not define these, and an
    // unrecognised key in a server entry is not worth the risk of the whole
    // entry being rejected.
    for (const k of ['envFile', 'dev', 'sandboxEnabled']) delete next[k];

    // Claude reads a `type`-less entry as stdio, so a remote server that omits
    // it is silently skipped at load with a message most people never see.
    // Fail the sync instead -- a generator that emits a config the host will
    // refuse is worse than no generator.
    if (next.url && !next.type) {
      throw new Error(
        `MCP server "${name}" has a "url" but no "type"; add "type": "http" (or "sse" / "ws").`,
      );
    }

    mcpServers[name] = next;
  }

  return { path: '.mcp.json', content: JSON.stringify({ mcpServers }, null, 2) + '\n' };
}

// ---------------------------------------------------------------------------
// Scoped instructions -> .claude/rules/*.md
//
// Copilot scopes an instruction file with an `applyTo` glob and injects it only
// when a matching file is in play. Claude's equivalent is `.claude/rules/*.md`
// with a `paths:` frontmatter glob list -- the SAME shape, so the translation is
// a rename, not a reduction.
//
// This used to write a `CLAUDE.md` into the directory each glob pointed at,
// because an earlier revision of this comment asserted "Claude has no per-file
// frontmatter scoping". That was false, and it was false in the same way as
// every other entry in section 12.9 of CONTROL-PLANE-NOTES: the mechanism was
// never looked for. `.claude/rules/` landed in 2.0.64, `paths:` conditionals in
// 2.1.69, and the installed 2.1.211 is itself a `.claude/rules/` bugfix release.
//
// What the directory scheme cost, measured against the real `applyTo` values:
//
//   src/**/*.tsx          -> src/CLAUDE.md          COARSENED (loads for .css, .json, ...)
//   src/**/*.ts           -> src/CLAUDE.md          COARSENED
//   src/app/**/*.tsx      -> src/app/CLAUDE.md      COARSENED (loads for route.ts, actions/*.ts)
//   vitest.config.mts     -> (nothing)              DROPPED -- no directory to attach to
//   playwright.config.ts  -> (nothing)              DROPPED
//
// The dropped pair is the one that mattered: `vitest.config.mts` holds the 90%
// coverage thresholds that AGENTS.md forbids lowering, `testing.instructions.md`
// names it in `applyTo`, and an agent editing it received none of that file's
// 5.6 KB of guidance. Declared, and silently unreachable.
//
// Verified on the installed 2.1.211, untrusted workspace, via three canary rules
// in a scratch repo: a rule with no `paths:` always loaded; a rule scoped to
// `nothing/**/*.zzz` never loaded; a rule scoped to the bare root file
// `vitest.config.mts` loaded only after that file was read.
// ---------------------------------------------------------------------------

function buildInstructionScopes() {
  const dir = join(ROOT, '.github', 'instructions');
  if (!existsSync(dir)) return [];

  const out = [];
  const unscoped = [];

  for (const file of readdirSync(dir).filter((f) => f.endsWith('.instructions.md'))) {
    const { fm, body } = splitFrontmatter(readFileSync(join(dir, file), 'utf8'));
    const title = file.replace(/\.instructions\.md$/, '');
    if (!fm?.applyTo) {
      // No glob means it applies everywhere. Root CLAUDE.md imports these by
      // hand -- emitting them as an unconditional rule would double them.
      unscoped.push(title);
      continue;
    }

    // Pass the globs through verbatim. `applyTo` and `paths:` are the same
    // dialect, so anything clever here can only lose fidelity.
    const globs = String(fm.applyTo)
      .split(',')
      .map((g) => g.trim())
      .filter(Boolean);
    if (!globs.length) continue;

    out.push({
      path: join('.claude', 'rules', `${title}.md`),
      content: [
        '---',
        `paths: [${globs.map((g) => JSON.stringify(g)).join(', ')}]`,
        '---',
        `<!-- ${BANNER} -->`,
        `<!-- from .github/instructions/${title}.instructions.md, scoped by its \`applyTo\` globs. -->`,
        '',
        body.trim(),
        '',
      ].join('\n'),
    });
  }

  if (unscoped.length) {
    console.log(
      `[sync-claude] unscoped instructions (import these from root CLAUDE.md): ${unscoped.join(', ')}`,
    );
  }

  return out;
}

function buildReadme() {
  const content = [
    '# .claude — generated',
    '',
    `> ${BANNER}`,
    '',
    'Do not edit anything in this directory. `.github/` is the single source of',
    'truth for the agent control plane; this tree is its Claude Code translation.',
    '',
    '| Generated | From |',
    '|---|---|',
    '| `.claude/agents/*.md` | `.github/agents/*.agent.md` |',
    '| `.claude/skills/*/` | `.github/skills/*/` |',
    '| `.claude/settings.json` | `.github/hooks/agentic-guard.json` + `permissions.json` |',
    '| `.claude/rules/*.md` | `.github/instructions/*.instructions.md` (via `applyTo` → `paths:`) |',
    '| `../.mcp.json` | `.vscode/mcp.json` |',
    '',
    'The hook scripts in `.github/hooks/scripts/` are shared verbatim — they already',
    'emit the `hookSpecificOutput` protocol both hosts read. Only the registration',
    'wrapper differs, which is what `settings.json` above provides.',
    '',
    '## Hooks vs permissions',
    '',
    'Copilot registers all four hooks because it has no native permission system —',
    'there, the hook *is* the mechanism. Claude has `permissions`, enforced in-process',
    'with no subprocess, so **Claude registers none of them.**',
    '',
    'Every `type: "command"` hook is spawned through `cmd /c` **without**',
    '`windowsHide`, so on Windows each one allocates a `conhost.exe` — a visible console',
    'window — and blocks the tool call for ~70–100 ms. Worse, when a hook *hangs* that',
    'window never closes: under `cmd /c` the node child never saw stdin close, blocked',
    'forever on the `end` event, and left `cmd.exe` and its console alive. The registered',
    '`timeout` did not reap them.',
    '',
    '| Hook | Claude | Why |',
    '|---|---|---|',
    ...Object.entries(CLAUDE_SKIP).map(
      ([name, why]) => `| \`${name}.mjs\` | not registered | ${why.replace(/\s+/g, ' ')} |`,
    ),
    '',
    'Net effect: **zero hook processes**. Nothing Claude does in this repo spawns a',
    'console window, and no guard can leak a process, because no guard is a process.',
    '',
    '### What the native rules cannot cover',
    '',
    'Corrected 2026-09-17 — this section previously claimed matching was prefix-only and',
    'that `pnpm test && rm -rf dist` slipped through as "a reviewed risk". That was wrong,',
    'and it understated the protection actually in place. Claude Code splits a command on',
    '`&&`, `||`, `;`, `|`, `|&`, `&` and newlines (and parses the PowerShell AST for the',
    'PowerShell tool), then applies **`deny` and `ask` when *any* subcommand matches** —',
    'including inside a subshell, a command substitution, or a loop body. `allow` runs the',
    'strict way instead: every subcommand must match or the command still prompts.',
    '',
    'What genuinely is not covered is a bare **flag**, because a flag is not a subcommand.',
    'Hence the explicit `--no-verify` deny rules, which this repo forbids outright.',
    '',
    'The real residue is elsewhere: `permissions.allow`, `permissions.additionalDirectories`',
    'and most `env` values **wait for workspace trust**, so on an untrusted folder every gate',
    'command prompts and no project-scope MCP server starts. `deny` and `ask` apply',
    'immediately, so an untrusted workspace fails safe rather than open. See',
    '`.github/CONTROL-PLANE-NOTES.md`.',
    '',
    '## Commands',
    '',
    '```',
    'pnpm agents:sync          regenerate',
    'pnpm agents:sync:check    fail if stale (no writes)',
    '```',
    '',
    '## Known translation gaps',
    '',
    '- **Tool names.** `execute` emits both `Bash` and `PowerShell`, and `agent` emits',
    '  both `Task` and `Agent`, because the shell and delegation tools are named',
    '  differently in the Claude Code CLI and the VS Code agent host. The field is an',
    '  allowlist, so the name that does not exist in a given host is inert. Run',
    '  `/agents` in Claude Code to confirm what actually resolved.',
    "- **`agents:` restriction.** Copilot's planner may only spawn a named set of",
    '  subagents. Claude grants delegation wholesale via the Task tool, so the',
    '  restriction is emitted as a prose directive instead of an enforced boundary.',
    '- **Model preference lists.** Copilot takes an ordered list; Claude takes one',
    '  model. The first Anthropic entry wins, and a GPT-only preference becomes',
    '  `inherit`.',
    "- **Instruction scoping.** Copilot's `applyTo` and Claude's `.claude/rules/`",
    '  `paths:` frontmatter are the same glob dialect, so each instruction file',
    '  becomes one rule file with its globs copied verbatim — no coarsening, and',
    '  root-file globs like `vitest.config.mts` keep their scope. Instruction files',
    '  with no `applyTo` are global — import them from the root `CLAUDE.md` by hand.',
    '',
  ].join('\n');
  return { path: join('.claude', 'README.md'), content };
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

const artifacts = [];

const agentDir = join(ROOT, '.github', 'agents');
for (const f of readdirSync(agentDir).filter((f) => f.endsWith('.agent.md'))) {
  artifacts.push(buildAgent(join(agentDir, f)));
}

const skillDir = join(ROOT, '.github', 'skills');
for (const name of readdirSync(skillDir)) {
  if (statSync(join(skillDir, name)).isDirectory()) artifacts.push(...buildSkill(skillDir, name));
}

artifacts.push(...buildInstructionScopes());
artifacts.push(...buildHookAssets());
artifacts.push(buildSettings(), buildMcp(), buildReadme());

const stale = artifacts.filter(({ path, content }) => {
  const abs = join(ROOT, path);
  return !existsSync(abs) || readFileSync(abs, 'utf8') !== content;
});

// This script used to scatter generated CLAUDE.md files through the product
// tree, where deleting a directory could not clean them. Scoped rules now live
// entirely under `.claude/rules/`, which IS cleaned wholesale above -- so this
// scan's remaining job is to sweep up the previous scheme's leftovers on the
// first sync after the migration, and to catch a stamped file someone copies
// somewhere unexpected later. Keying on the banner means a hand-written
// CLAUDE.md is never at risk -- it simply does not carry the stamp. That also
// keeps the cloned research repos under dev-tools/ safe: none of their
// CLAUDE.md files are stamped, so none are ever considered.
const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  '.claude',
  '.github',
  'coverage',
  'dist',
  'build',
  'out',
  'test-results',
  'playwright-report',
]);

function findGenerated(dir = ROOT, depth = 0) {
  const out = [];
  if (depth > 6) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      out.push(...findGenerated(join(dir, entry.name), depth + 1));
    } else if (entry.name === 'CLAUDE.md' && dir !== ROOT) {
      const abs = join(dir, entry.name);
      if (readFileSync(abs, 'utf8').includes(BANNER)) out.push(relative(ROOT, abs));
    }
  }
  return out;
}

const claimed = new Set(artifacts.map((a) => a.path));
const orphans = findGenerated().filter((p) => !claimed.has(p));

lintStaleClaims();

if (CHECK) {
  if (
    stale.length ||
    orphans.length ||
    promiseWarnings.length ||
    dropWarnings.length ||
    claimWarnings.length
  ) {
    if (stale.length || orphans.length) {
      console.error(
        `[sync-claude] ${stale.length} stale, ${orphans.length} orphaned. Run \`pnpm agents:sync\`.`,
      );
      for (const { path } of stale) console.error(`  stale    ${path.split(sep).join('/')}`);
      for (const path of orphans) console.error(`  orphan   ${path.split(sep).join('/')}`);
    }
    // Unlike stale/orphan, these three are NOT fixed by re-running the sync -- the
    // source file itself is contradictory. Say so, or the operator loops.
    for (const w of claimWarnings) console.error(`  claim    ${w}`);
    for (const w of promiseWarnings) console.error(`  promise  ${w}`);
    for (const w of dropWarnings) console.error(`  dropped  ${w}`);
    process.exit(1);
  }
  console.log(`[sync-claude] up to date (${artifacts.length} files).`);
  process.exit(0);
}

for (const path of orphans) rmSync(join(ROOT, path), { force: true });

// Clear generated trees so a deleted source agent does not leave a stale twin.
// Scoped to the three directories this script owns; `.claude/` itself is left
// alone so any hand-written local settings alongside it survive.
for (const d of [
  join(ROOT, '.claude', 'agents'),
  join(ROOT, '.claude', 'skills'),
  join(ROOT, '.claude', 'rules'),
]) {
  if (existsSync(d)) rmSync(d, { recursive: true, force: true });
}

for (const { path, content } of artifacts) {
  const abs = join(ROOT, path);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, 'utf8');
}

const agents = artifacts.filter((a) => a.path.includes(join('.claude', 'agents'))).length;
const skills = artifacts.filter((a) => a.path.endsWith('SKILL.md')).length;
const scoped = artifacts.filter((a) => a.path.includes(join('.claude', 'rules'))).length;
console.log(
  `[sync-claude] wrote ${artifacts.length} files — ${agents} agents, ${skills} skills, ${scoped} scoped rules, settings.json, .mcp.json`,
);
if (orphans.length) console.log(`[sync-claude] removed ${orphans.length} orphaned file(s).`);
if (claimWarnings.length) {
  console.log(
    `\n[sync-claude] ${claimWarnings.length} corrected claim(s) still standing — \`agents:sync:check\` fails on these:`,
  );
  for (const w of claimWarnings) console.log(`  ${w}`);
}
if (promiseWarnings.length) {
  console.log(
    `\n[sync-claude] ${promiseWarnings.length} capability promise(s) an agent cannot keep — \`agents:sync:check\` fails on these:`,
  );
  for (const w of promiseWarnings) console.log(`  ${w}`);
}
if (dropWarnings.length) {
  console.log(
    `\n[sync-claude] ${dropWarnings.length} source frontmatter key(s) not emitted — \`agents:sync:check\` fails on these:`,
  );
  for (const w of dropWarnings) console.log(`  ${w}`);
}
for (const { path } of artifacts)
  console.log(`  ${relative(ROOT, join(ROOT, path)).split(sep).join('/')}`);

// MCP servers are pinned by absolute path rather than launched with `npx -y`,
// which trades "always latest" for reproducibility. That trade is only honest
// if something tells you when you have fallen behind, so the drift check rides
// along here -- throttled to once a week, and deliberately NOT on the --check
// path above, which runs in hooks and CI where a network call has no business.
//
// Non-fatal by construction: an offline machine, a proxy, or a deleted server
// install must never be able to fail `pnpm agents:sync`.
try {
  const { checkDrift, formatNotice } = await import('./mcp-versions.mjs');
  const notice = formatNotice(await checkDrift({ throttle: true }));
  if (notice) console.log(`\n${notice}`);
} catch (err) {
  console.log(`[sync-claude] MCP version check skipped: ${err.message}`);
}
